<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">




<!-- macro arms -->
<xacro:macro name="centauro_arm" params="arm_num rot parent *origin">
	
<!-- LINKS -->
<!-- shoulder yaw-roll-->
   <link name="arm${arm_num}_1">
      <inertial>
         <origin xyz="${Shoulder_1_x} ${rot*Shoulder_1_y} ${Shoulder_1_z}"/>
         <mass value="${Shoulder_1_mass}"/>
         <inertia ixx="${Shoulder_1_xx}" ixy="${rot*Shoulder_1_xy}" ixz="${Shoulder_1_xz}" iyy="${Shoulder_1_yy}" iyz="${rot*Shoulder_1_yz}" izz="${Shoulder_1_zz}"/>
      </inertial>

      <visual>
   <origin xyz="0.0 0.0 0.0"  rpy="0.0 0.0 0.0"/>
   <geometry>
      <mesh filename="package://centauro_urdf/meshes/ShoulderPitch.STL" scale="0.001 ${-rot*0.001} 0.001" />
   </geometry>
         <material name="dark_grey"/>
      </visual>
	
      <collision>
   <origin xyz="0.0 0.0 0.0"  rpy="0.0 0.0 0.0"/>
   <geometry>
      <mesh filename="package://centauro_urdf/meshes/simple/ShoulderPitch.STL" scale="0.001 ${-rot*0.001} 0.001" />
   </geometry>
      </collision>
   </link>
<!-- shoulder yaw-roll-->

<!-- shoulder roll-pitch-->
   <link name="arm${arm_num}_2">
      <inertial>
         <origin xyz="${Shoulder_2_x} ${rot*Shoulder_2_y} ${Shoulder_2_z}"/>
         <mass value="${Shoulder_2_mass}"/>
         <inertia ixx="${Shoulder_2_xx}" ixy="${rot*Shoulder_2_xy}" ixz="${Shoulder_2_xz}" iyy="${Shoulder_2_yy}" iyz="${rot*Shoulder_2_yz}" izz="${Shoulder_2_zz}"/>
      </inertial>

      <visual>
         <origin xyz="0.0 0.0 0.0"  rpy="0.0 0.0 0.0"/>
   <geometry>
      <mesh filename="package://centauro_urdf/meshes/ShoulderRoll.STL" scale="0.001 ${-rot*0.001} 0.001" />
   </geometry>
      </visual>
	
      <collision>
         <origin xyz="0.0 0.0 0.0"  rpy="0.0 0.0 0.0"/>
   <geometry>
      <mesh filename="package://centauro_urdf/meshes/simple/ShoulderRoll.STL" scale="0.001 ${-rot*0.001} 0.001" />
   </geometry>
      </collision>
   </link>
<!-- shoulder roll-pitch-->
	
<!-- shoulder-elbow -->
   <link name="arm${arm_num}_3">
      <inertial>
         <origin xyz="${Shoulder_3_x} ${rot*Shoulder_3_y} ${Shoulder_3_z}"/>
         <mass value="${Shoulder_3_mass}"/>
         <inertia ixx="${Shoulder_3_xx}" ixy="${rot*Shoulder_3_xy}" ixz="${Shoulder_3_xz}" iyy="${Shoulder_3_yy}" iyz="${rot*Shoulder_3_yz}" izz="${Shoulder_3_zz}"/>
</inertial>

      <visual>
         <origin xyz="0.0 0.0 0.0"  rpy="0.0 0.0 0.0"/>
   <geometry>
      <mesh filename="package://centauro_urdf/meshes/ShoulderYaw.STL" scale="0.001 ${-rot*0.001} 0.001" />
   </geometry>
         <material name="dark_grey"/>
      </visual>

      <collision>
         <origin xyz="0.0 0.0 0.0"  rpy="0.0 0.0 0.0"/>
   <geometry>
      <mesh filename="package://centauro_urdf/meshes/simple/ShoulderYaw.STL" scale="0.001 ${-rot*0.001} 0.001" />
   </geometry>
      </collision>
   </link>
<!-- /shoulder-elbow -->

<!-- elbow yaw-pitch -->
   <link name="arm${arm_num}_4">
      <inertial>
         <origin xyz="${Elbow_1_x} ${rot*Elbow_1_y} ${Elbow_1_z}"/>
         <mass value="${Elbow_1_mass}"/>
         <inertia ixx="${Elbow_1_xx}" ixy="${rot*Elbow_1_xy}" ixz="${Elbow_1_xz}" iyy="${Elbow_1_yy}" iyz="${rot*Elbow_1_yz}" izz="${Elbow_1_zz}"/>
      </inertial>

      <visual>
         <origin xyz="0.0 0.0 0.0"  rpy="0.0 0.0 0.0"/>
   <geometry>
      <mesh filename="package://centauro_urdf/meshes/Elbow.STL" scale="0.001 ${-rot*0.001} 0.001" />
   </geometry>
      </visual>
	
      <collision>
         <origin xyz="0.0 0.0 0.0"  rpy="0.0 0.0 0.0"/>
   <geometry>
      <mesh filename="package://centauro_urdf/meshes/simple/Elbow.STL" scale="0.001 ${-rot*0.001} 0.001" />
   </geometry>
      </collision>
   </link>
<!-- /elbow yaw-pitch -->

<!-- elbow-wrist -->
   <link name="arm${arm_num}_5">
      <inertial>
         <origin xyz="${Wrist_1_x} ${rot*Wrist_1_y} ${Wrist_1_z}"/>
         <mass value="${Wrist_1_mass}"/>
         <inertia ixx="${Wrist_1_xx}" ixy="${rot*Wrist_1_xy}" ixz="${Wrist_1_xz}" iyy="${Wrist_1_yy}" iyz="${rot*Wrist_1_yz}" izz="${Wrist_1_zz}"/>
</inertial>
      <visual>
         <origin xyz="0.0 0.0 0.0"  rpy="0.0 0.0 0.0"/>
   <geometry>
      <mesh filename="package://centauro_urdf/meshes/Forearm.STL" scale="0.001 ${-rot*0.001} 0.001" />
   </geometry>
         <material name="dark_grey"/>
      </visual>

      <collision>
         <origin xyz="0.0 0.0 0.0"  rpy="0.0 0.0 0.0"/>
   <geometry>
      <mesh filename="package://centauro_urdf/meshes/simple/Forearm.STL" scale="0.001 ${-rot*0.001} 0.001" />
   </geometry>
      </collision>
   </link>
<!-- /elbow-wrist -->

<!-- wrist yaw-pitch -->
   <link name="arm${arm_num}_6">
      <inertial>
         <origin xyz="${Wrist_2_x} ${rot*Wrist_2_y} ${Wrist_2_z}"/>
         <mass value="${Wrist_2_mass}"/>
         <inertia ixx="${Wrist_2_xx}" ixy="${rot*Wrist_2_xy}" ixz="${Wrist_2_xz}" iyy="${Wrist_2_yy}" iyz="${rot*Wrist_2_yz}" izz="${Wrist_2_zz}"/>
</inertial>

      <visual>
         <origin xyz="0.0 0.0 0.0"  rpy="0.0 0.0 0.0"/>
   <geometry>
      <mesh filename="package://centauro_urdf/meshes/ForearmPitch.STL" scale="0.001 ${-rot*0.001} 0.001" />
   </geometry>
      </visual>
	
      <collision>
         <origin xyz="0.0 0.0 0.0"  rpy="0.0 0.0 0.0"/>
   <geometry>
      <mesh filename="package://centauro_urdf/meshes/simple/ForearmPitch.STL" scale="0.001 ${-rot*0.001} 0.001" />
   </geometry>
      </collision>
   </link>
<!-- /wrist yaw-pitch -->

   <link name="arm${arm_num}_7">
      <inertial>
         <origin xyz="${Wrist_3_x} ${rot*Wrist_3_y} ${Wrist_3_z}"/>
         <mass value="${Wrist_3_mass}"/>
         <inertia ixx="${Wrist_3_xx}" ixy="${rot*Wrist_3_xy}" ixz="${Wrist_3_xz}" iyy="${Wrist_3_yy}" iyz="${rot*Wrist_3_yz}" izz="${Wrist_3_zz}"/>
      </inertial>

      <visual>
         <origin xyz="0.0 0.0 0.0"  rpy="0.0 0.0 0.0"/>
   <geometry>
      <mesh filename="package://centauro_urdf/meshes/ForearmYaw.STL" scale="0.001 ${-rot*0.001} 0.001" />
   </geometry>
         <material name="dark_grey"/>
      </visual>

      <collision>
         <origin xyz="0.0 0.0 0.0"  rpy="0.0 0.0 0.0"/>
   <geometry>
      <mesh filename="package://centauro_urdf/meshes/simple/ForearmYaw.STL" scale="0.001 ${-rot*0.001} 0.001" />
   </geometry>
      </collision>
   </link>

<!-- /LINKS -->

<!-- JOINTS -->
<!-- shoulder yaw -->
   <joint name="j_arm${arm_num}_1" type="revolute">
      <parent link="${parent}"/>
      <child link="arm${arm_num}_1"/>
      <xacro:insert_block name="origin"/>
      <axis xyz="0 1 0"/>
      <limit lower="${j_arm_1_lower[arm_num-1]}" upper="${j_arm_1_upper[arm_num-1]}" effort="${j_arm_1_torque[arm_num-1]}" velocity="${j_arm_1_velocity[arm_num-1]}"/>
   </joint>
<!-- /shoulder yaw -->
	
<!-- shoulder roll -->
   <joint name="j_arm${arm_num}_2" type="revolute">
      <parent link="arm${arm_num}_1"/>
      <child link="arm${arm_num}_2"/>
      <origin xyz="${Shoulder_2_Ox} ${rot*Shoulder_2_Oy} ${Shoulder_2_Oz}" rpy="${rot*Shoulder_2_roll} ${Shoulder_2_pitch} ${Shoulder_2_yaw}"/>
      <axis xyz="1 0 0"/>
      <limit lower="${j_arm_2_lower[arm_num-1]}" upper="${j_arm_2_upper[arm_num-1]}" effort="${j_arm_2_torque[arm_num-1]}" velocity="${j_arm_2_velocity[arm_num-1]}"/>
   </joint>
<!-- /shoulder roll -->

<!-- shoulder pitch-->
   <joint name="j_arm${arm_num}_3" type="revolute">
      <parent link="arm${arm_num}_2"/>
      <child link="arm${arm_num}_3"/>
      <origin xyz="${Shoulder_3_Ox} ${Shoulder_3_Oy} ${Shoulder_3_Oz}"/>
      <axis xyz="0 0 1"/>
      <limit lower="${j_arm_3_lower[arm_num-1]}" upper="${j_arm_3_upper[arm_num-1]}" effort="${j_arm_3_torque[arm_num-1]}" velocity="${j_arm_3_velocity[arm_num-1]}"/>
   </joint>
<!-- /shoulder pitch -->
	
<!-- elbow yaw -->
   <joint name="j_arm${arm_num}_4" type="revolute">
      <parent link="arm${arm_num}_3"/>
      <child link="arm${arm_num}_4"/>
      <origin xyz="${Elbow_1_Ox} ${rot*Elbow_1_Oy} ${Elbow_1_Oz}"/>
      <axis xyz="0 1 0"/>
      <limit lower="${j_arm_4_lower[arm_num-1]}" upper="${j_arm_4_upper[arm_num-1]}" effort="${j_arm_4_torque[arm_num-1]}" velocity="${j_arm_4_velocity[arm_num-1]}"/>
   </joint>
<!-- /elbow yaw -->

<!-- elbow pitch-->
   <joint name="j_arm${arm_num}_5" type="revolute">
      <parent link="arm${arm_num}_4"/>
      <child link="arm${arm_num}_5"/>
      <origin xyz="${Wrist_1_Ox} ${rot*Wrist_1_Oy} ${Wrist_1_Oz}"/>
      <axis xyz="0 0 1"/>
      <limit lower="${j_arm_5_lower[arm_num-1]}" upper="${j_arm_5_upper[arm_num-1]}" effort="${j_arm_5_torque[arm_num-1]}" velocity="${j_arm_5_velocity[arm_num-1]}"/>
   </joint>
<!-- /elbow pitch-->
	
<!-- wrist yaw-->
   <joint name="j_arm${arm_num}_6" type="revolute">
      <parent link="arm${arm_num}_5"/>
      <child link="arm${arm_num}_6"/>
      <origin xyz="${Wrist_2_Ox} ${rot*Wrist_2_Oy} ${Wrist_2_Oz}"/>
      <axis xyz="0 1 0"/>
      <limit lower="${j_arm_6_lower[arm_num-1]}" upper="${j_arm_6_upper[arm_num-1]}" effort="${j_arm_6_torque[arm_num-1]}" velocity="${j_arm_6_velocity[arm_num-1]}"/>
   </joint>
<!-- /wrist yaw-->
	
<!-- wrist pitch-->
   <joint name="j_arm${arm_num}_7" type="revolute">
      <parent link="arm${arm_num}_6"/>
      <child link="arm${arm_num}_7"/>
      <origin xyz="${Wrist_3_Ox} ${rot*Wrist_3_Oy} ${Wrist_3_Oz}"/>
      <axis xyz="0 0 1"/>
      <limit lower="${j_arm_7_lower[arm_num-1]}" upper="${j_arm_7_upper[arm_num-1]}" effort="${j_arm_7_torque[arm_num-1]}" velocity="${j_arm_7_velocity[arm_num-1]}"/>
   </joint>
<!-- wrist pitch-->

<!-- force-troque sensor -->


<!-- end-effector -->
<!-- wrist pitch-->
   <joint name="j_ft_${arm_num}" type="fixed">
      <parent link="arm${arm_num}_7"/>
      <child link="ft_arm${arm_num}"/>
      <origin xyz="${Ft_arm_Ox} ${Ft_arm_Oy} ${Ft_arm_Oz}" rpy="${Ft_arm_roll} ${Ft_arm_pitch} ${Ft_arm_yaw}" />
      <axis xyz="0 0 1"/>
      <limit lower="0.0" upper="0.0" effort="0" velocity="0"/>
   </joint>

<!-- wrist pitch-->
   <link name="ft_arm${arm_num}">
      <inertial>
         <origin xyz="${Ft_arm_x} ${rot*Ft_arm_y} ${Ft_arm_z}"/>
         <mass value="${Ft_arm_mass}"/>
         <inertia ixx="${Ft_arm_xx}" ixy="${rot*Ft_arm_xy}" ixz="${Ft_arm_xz}" iyy="${Ft_arm_yy}" iyz="${rot*Ft_arm_yz}" izz="${Ft_arm_zz}"/>
      </inertial>
      <!--visual>
         <origin xyz="0.0 0.0 0.0"  rpy="${PI} 0.0 0.0"/>
   <geometry>
      <mesh filename="package://centauro_urdf/meshes/Wrist.STL" scale="0.001 ${-rot*0.001} 0.001" />
   </geometry>
      </visual-->
	
      <!--collision>
         <origin xyz="0.0 0.0 0.0"  rpy="${PI} 0.0 0.0"/>
   <geometry>
      <mesh filename="package://centauro_urdf/meshes/simple/Wrist.STL" scale="0.001 ${-rot*0.001} 0.001" />
   </geometry>
      </collision-->

   </link>



</xacro:macro>
<!-- /macro arms -->

</robot>
