<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

<!-- macro legs -->
<xacro:macro name="centauro_leg" params="leg_num origin_x origin_y mirror">

<link name="hip1_${leg_num}">

	<inertial>
		<origin xyz="${Leg_1_x} ${mirror*Leg_1_y} ${Leg_1_z}" />
		<mass value="${Leg_1_mass}"/> <!-- org: 2 -->
		<inertia ixx="${Leg_1_xx}" ixy="${mirror*Leg_1_xy}" ixz="${Leg_1_xz}" iyy="${Leg_1_yy}" iyz="${mirror*Leg_1_yz}" izz="${Leg_1_zz}"/>
	</inertial>

   <visual>
      <origin xyz="0.0 0.0 0.0"  rpy="0.0 0.0 0.0"/>
      <geometry>
         <mesh filename="package://centauro_urdf/meshes/v2/hip-yaw.stl" scale="0.001 ${mirror*0.001} 0.001" />
      </geometry>
      <material name="dark_grey"/>
   </visual>
	
   <collision>
      <origin xyz="0.0 0.0 0.0"  rpy="0.0 0.0 0.0"/>
      <geometry>
         <mesh filename="package://centauro_urdf/meshes/v2/collision/hip-yaw.stl" scale="0.001 ${mirror*0.001} 0.001" />
      </geometry>
   </collision>

</link>

<link name="hip2_${leg_num}">
	<inertial>
		<origin xyz="${Leg_2_x} ${Leg_2_y} ${mirror*Leg_2_z}"/>	
		<mass value="${Leg_2_mass}"/> <!-- org: 4.5 -->
		<inertia ixx="${Leg_2_xx}" ixy="${Leg_2_xy}" ixz="${mirror*Leg_2_xz}" iyy="${Leg_2_yy}" iyz="${mirror*Leg_2_yz}" izz="${Leg_2_zz}"/> 
	</inertial>

   <visual>
      <origin xyz="0.0 0.0 0.0"  rpy="0.0 0.0 0.0"/>
      <geometry>
         <mesh filename="package://centauro_urdf/meshes/v2/hip-pitch.stl" scale="0.001 0.001 ${mirror*0.001}" />
      </geometry>
   </visual>
	
   <collision>
      <origin xyz="0.0 0.0 0.0"  rpy="0.0 0.0 0.0"/>
      <geometry>
         <mesh filename="package://centauro_urdf/meshes/v2/collision/hip-pitch.stl" scale="0.001 0.001 ${mirror*0.001}" />
      </geometry>
   </collision>

</link>

<xacro:if value="${USE_STICKS}">
<link name="knee_${leg_num}">
<inertial> 
	<mass value="${1.1927236}"/>
    <origin xyz="${1.9572282e+02*mmTom} ${-1.4549221e+01*mmTom} ${-2.0785942e+01*mmTom}" rpy="0.0 0.0 0.0"/>
	<!--origin xyz="${1.4549221e+01*mmTom} ${-2.0785942e+01*mmTom} ${-1.9572282e+02*mmTom}" rpy="0.0 0.0 0.0"/-->      
	<!--inertia ixx="${3.5313402e+04*mm2Tom2}"  ixy="${0.0*mm2Tom2}"  ixz="${1.1029574e-01*mm2Tom2}" iyy="${3.5530025e+04*mm2Tom2}" iyz="${-6.0307457e+02*mm2Tom2}" izz="${1.3302597e+03*mm2Tom2}" /-->
    <inertia ixx="${1.3302597e+03*mm2Tom2}"  ixy="${6.0307457e+02*mm2Tom2}"  ixz="${0.0*mm2Tom2}" iyy="${3.5313402e+04*mm2Tom2}" iyz="${-1.1029574e-01*mm2Tom2}" izz="${3.5530025e+04*mm2Tom2}" />
</inertial>

<visual>
      <origin xyz="0 0 0" rpy="${PI_2} 0 ${-PI_2}"/>
      <material name="black"/>
      <geometry name="${leg_num}_stick_visual">
        <mesh filename="package://centauro_urdf/meshes/front_right_stick.stl" scale="${mmTom} ${mmTom} ${mmTom}"/>
      </geometry>
</visual> 

<collision>
      <origin xyz="0 0 0" rpy="${PI_2} 0 ${-PI_2}"/>
      <geometry name="${leg_num}_stick_collision">
        <mesh filename="package://centauro_urdf/meshes/simple/front_right_stick.stl" scale="${mmTom} ${mmTom} ${mmTom}"/>
      </geometry>             
</collision>  
</link>
</xacro:if>

<xacro:unless value="${USE_STICKS}">
<link name="knee_${leg_num}">
	<inertial>
		<origin xyz="${Leg_3_x} ${Leg_3_y} ${mirror*Leg_3_z}"/>
		<mass value="${Leg_3_mass}"/>  <!-- org: 3.5, foot un modeled-->
		<inertia ixx="${Leg_3_xx}" ixy="${Leg_3_xy}" ixz="${mirror*Leg_3_xz}" iyy="${Leg_3_yy}" iyz="${mirror*Leg_3_yz}" izz="${Leg_3_zz}"/>
	</inertial>

   <visual>
      <origin xyz="0.0 0.0 0.0"  rpy="0.0 0.0 0.0"/>
      <geometry>
         <mesh filename="package://centauro_urdf/meshes/v2/knee.stl" scale="0.001 0.001 ${mirror*0.001}" />
      </geometry>
      <material name="dark_grey"/>
   </visual>
	
   <collision>
      <origin xyz="0.0 0.0 0.0"  rpy="0.0 0.0 0.0"/>
      <geometry>
         <mesh filename="package://centauro_urdf/meshes/v2/collision/knee.stl" scale="0.001 0.001 ${mirror*0.001}" />
      </geometry>
   </collision>
</link>

<link name="ankle1_${leg_num}">
	<inertial>
		<origin xyz="${Ankle_1_x} ${Ankle_1_y} ${mirror*Ankle_1_z}"/>
		<mass value="${Ankle_1_mass}"/>  <!-- org: 3.5, foot un modeled-->
		<inertia ixx="${Ankle_1_xx}" ixy="${Ankle_1_xy}" ixz="${mirror*Ankle_1_xz}" iyy="${Ankle_1_yy}" iyz="${mirror*Ankle_1_yz}" izz="${Ankle_1_zz}"/>
	</inertial>

   <visual>
      <origin xyz="0.0 0.0 0.0"  rpy="0.0 0.0 0.0"/>
      <geometry>
         <mesh filename="package://centauro_urdf/meshes/v2/ankle-pitch.stl" scale="0.001 0.001 ${mirror*0.001}" />
      </geometry>
   </visual>
	
   <collision>
      <origin xyz="0.0 0.0 0.0"  rpy="0.0 0.0 0.0"/>
      <geometry>
         <mesh filename="package://centauro_urdf/meshes/v2/collision/ankle-pitch.stl" scale="0.001 0.001 ${mirror*0.001}" />
      </geometry>
   </collision>
</link>

<link name="ankle2_${leg_num}">
	<inertial>
		<origin xyz="${Ankle_2_x} ${mirror*Ankle_2_y} ${Ankle_2_z}"/>
		<mass value="${Ankle_2_mass}"/>  <!-- org: 3.5, foot un modeled-->
		<inertia ixx="${Ankle_2_xx}" ixy="${mirror*Ankle_2_xy}" ixz="${Ankle_2_xz}" iyy="${Ankle_2_yy}" iyz="${mirror*Ankle_2_yz}" izz="${Ankle_2_zz}"/>
	</inertial>

   <visual>
      <origin xyz="0.0 0.0 0.0"  rpy="0.0 0.0 0.0"/>
      <geometry>
         <mesh filename="package://centauro_urdf/meshes/v2/ankle-yaw.stl" scale="0.001 ${mirror*0.001} 0.001" />
      </geometry>
      <material name="dark_grey"/>
   </visual>
	
   <collision>
      <origin xyz="0.0 0.0 0.0"  rpy="0.0 0.0 0.0"/>
      <geometry>
         <mesh filename="package://centauro_urdf/meshes/v2/collision/ankle-yaw.stl" scale="0.001 ${mirror*0.001} 0.001" />
      </geometry>
   </collision>
</link>

<link name="wheel_${leg_num}">
	<inertial>
		<origin xyz="${Wheel_x} ${Wheel_y} ${mirror*Wheel_z}"/>
		<mass value="${Wheel_mass}"/>
		<inertia ixx="${Wheel_xx}" ixy="${Wheel_xy}" ixz="${mirror*Wheel_xz}" iyy="${Wheel_yy}" iyz="${mirror*Wheel_yz}" izz="${Wheel_zz}"/>
	</inertial>

   <visual>
      <origin xyz="0.0 0.0 0.0"  rpy="0.0 0.0 0.0"/>
      <geometry>
         <mesh filename="package://centauro_urdf/meshes/v2/wheel.stl" scale="0.001 0.001 ${mirror*0.001}" />
      </geometry>
      <material name="black"/>
   </visual>
	
	<collision>
		<origin xyz="0 0 0" rpy="0 0 0"/>
		<geometry>
			<cylinder length="0.11" radius="0.078"/>
      </geometry>
	</collision>
</link> 



</xacro:unless>

<!-- *****************************-->
<link name="contact_${leg_num}"/>

<joint name="contact_joint_${leg_num}" type="fixed">
	<parent link="ankle2_${leg_num}"/>
	<child link="contact_${leg_num}"/>
	<origin xyz="0 0 -0.176" rpy="0 0 0"/>
</joint>

<!-- ******************************** -->

<joint name="hip_yaw_${leg_num}" type="revolute">
	<parent link="pelvis"/>
	<child link="hip1_${leg_num}"/>
	<origin xyz="${origin_x*Leg_1_Ox} ${origin_y*Leg_1_Oy} ${Leg_1_Oz}" rpy="${Leg_1_roll} ${Leg_1_pitch} ${Leg_1_yaw}"/>
	<axis xyz="0 0 -1"/>
   <limit lower="${hip_yaw_lower[leg_num-1]}" upper="${hip_yaw_upper[leg_num-1]}" effort="${motor_A_effort}" velocity="${motor_A_velocity}"/> <!-- 200 Nm, 1 rad/s-->
</joint>

<joint name="hip_pitch_${leg_num}" type="revolute">
	<parent link="hip1_${leg_num}"/>
	<child link="hip2_${leg_num}"/>
	<origin xyz="${Leg_2_Ox} ${mirror*Leg_2_Oy} ${Leg_2_Oz}" rpy="${Leg_2_roll} ${Leg_2_pitch} ${Leg_2_yaw}"/>
	<axis xyz="0 0 ${mirror}"/>
   <limit lower="${hip_pitch_lower[leg_num-1]}" upper="${hip_pitch_upper[leg_num-1]}" effort="${motor_A_effort}" velocity="${motor_A_velocity}"/> <!-- 200 Nm, 1 rad/s-->
</joint>

<xacro:if  value="${USE_STICKS}">
<joint name="knee_pitch_${leg_num}" type="revolute">
	<parent link="hip2_${leg_num}"/>
	<child link="knee_${leg_num}"/>
	<origin xyz="${Leg_3_Ox} ${Leg_3_Oy} ${Leg_3_Oz}" rpy="${Leg_3_roll} ${Leg_3_pitch} ${Leg_3_yaw}"/>
	<axis xyz="0 0 1"/>
   <limit lower="${knee_pitch_lower[leg_num-1]}" upper="${knee_pitch_upper[leg_num-1]}" effort="${motor_A_effort}" velocity="${motor_A_velocity}"/> <!-- 200 Nm, 1 rad/s-->
</joint>
</xacro:if>

<xacro:unless value="${USE_STICKS}">
<joint name="knee_pitch_${leg_num}" type="revolute">
	<parent link="hip2_${leg_num}"/>
	<child link="knee_${leg_num}"/>
	<origin xyz="${Leg_3_Ox} ${Leg_3_Oy} ${mirror*Leg_3_Oz}" rpy="${Leg_3_roll} ${Leg_3_pitch} ${Leg_3_yaw}"/>
	<axis xyz="0 0 ${mirror}"/>
   <limit lower="${knee_pitch_lower[leg_num-1]}" upper="${knee_pitch_upper[leg_num-1]}" effort="${motor_A_effort}" velocity="${motor_A_velocity}"/> <!-- 200 Nm, 1 rad/s-->
</joint>


<joint name="ankle_pitch_${leg_num}" type="revolute">
	<parent link="knee_${leg_num}"/>
	<child link="ankle1_${leg_num}"/>
	<origin xyz="${Ankle_1_Ox} ${Ankle_1_Oy} ${mirror*Ankle_1_Oz}" rpy="${Ankle_1_roll} ${Ankle_1_pitch} ${Ankle_1_yaw}"/>
	<axis xyz="0 0 ${mirror}"/>
   <limit lower="${ankle_pitch_lower[leg_num-1]}" upper="${ankle_pitch_upper[leg_num-1]}" effort="${motor_B_effort}" velocity="${motor_B_velocity}"/> <!-- 98 Nm, 1 rad/s-->
</joint>

<joint name="ankle_yaw_${leg_num}" type="revolute">
	<parent link="ankle1_${leg_num}"/>
	<child link="ankle2_${leg_num}"/>
	<origin xyz="${Ankle_2_Ox} ${Ankle_2_Oy} ${mirror*Ankle_2_Oz}" rpy="${Ankle_2_roll} ${Ankle_2_pitch} ${Ankle_2_yaw}"/>
	<axis xyz="0 0 -1"/>
   <limit lower="${ankle_yaw_lower[leg_num-1]}" upper="${ankle_yaw_upper[leg_num-1]}" effort="${motor_C_effort}" velocity="${motor_C_velocity}"/>  <!-- 23 Nm, 1 rad/s-->
</joint>

<joint name="j_wheel_${leg_num}" type="continuous">
	<parent link="ankle2_${leg_num}"/>
	<child link="wheel_${leg_num}"/>
	<origin xyz="${Wheel_Ox} ${mirror*Wheel_Oy} ${Wheel_Oz}" rpy="${Wheel_roll} ${Wheel_pitch} ${Wheel_yaw}"/>
	<axis xyz="0 0 ${mirror}"/>
   <limit  effort="${motor_C_effort}" velocity="${motor_C_velocity}"/>  <!-- 23 Nm, 1 rad/s-->
</joint>
</xacro:unless>

</xacro:macro>
<!-- /macro legs -->

</robot>
